#/bin/bash

## Name		sysunconfig.sh
## Version:	0.1
## Author:      Pablo Endres <epablo@pabloendres.com> 14.11.2012
## Description: Prepares CentOS 6.x machines for clonning
## Licence:	GPLv3
## Updates:
# * 2013-01-28	Edited the basic ifcfg file


## Copyright (C) 2012 Pablo Endres <epablo@pabloendres.com>

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

ROOT_PASSWORD=$(uuidgen | tail -c 13)

# Clear the udev rules regaring the MAC Address of the existing network interfaces
cat <<END_SCRIPT > /etc/udev/rules.d/70-persistent-net.rules
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

END_SCRIPT

# Clean up YUM
yum clean all


# Delete network scripts for all NICs
rm -f /etc/sysconfig/networking/devices/ifcfg-eth*
rm -f /etc/sysconfig/networking/profiles/default/ifcfg-eth*
rm -f /etc/sysconfig/network-scripts/ifcfg-eth*

cat <<END_SCRIPT > /etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
ONBOOT=yes
PROTO=dhcp
BOOTPROTO=dhcp
TYPE=Ethernet
USERCTL=no
PEERDNS=yes
IPV6INIT=no

END_SCRIPT

# Delete the SSH keys
rm -f /etc/ssh/ssh_host_*

# Clear the log files
find /var/log/ -type f| xargs rm -f
#rm -rf /var/log/*
rm -f /root/.bash_history /admin-user/.bash_history 

# Recreate these files
#mkdir /var/log/sa/ /var/log/prelink/
touch /var/log/audit/audit.log
chown root:root /var/log/audit/audit.log
chmod 600 /var/log/audit/audit.log
restorecon -R -r /var/log/audit/

# set password for local user
echo "root:${ROOT_PASSWORD}" | chpasswd
echo "The new password for root is: "$ROOT_PASSWORD
