#/bin/bash

## Name		sysunconfig.sh
## Version:	0.1
## Author:      Pablo Endres <epablo@pabloendres.com> 03.07.2013
## Description: Prepares CentOS 6.x machines for clonning
## Licence:	GPLv3
## Updates:


## Copyright (C) 2013 Pablo Endres <epablo@pabloendres.com>

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.



# Clear the udev rules regaring the MAC Address of the existing network interfaces
cat <<END_SCRIPT > /etc/udev/rules.d/70-persistent-net.rules
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

END_SCRIPT

# Delete the SSH keys
rm -f /etc/ssh/ssh_host_*

# Clear the log files
for i in /var/log/wtmp /var/log/warn /var/log/messages /var/log/lastlog /var/log/mail /var/log/btmp
do
	> $i
done
rm -f /root/.bash_history /home/admin-user/.bash_history 





